apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
data:
  MP3_QUEUE: "mp3"
  VIDEO_QUEUE: "video"
  MONGODB_VIDEOS_URI: "mongodb://mongodb:27017/videos"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  FLASK_ENV: "production"